### cp8_4~7 예외처리방법

1. 예외 처리하기 (try_catch)

   1. printStackTrace() : 예외발생 당시의 호출스택에 있던 메서드 정보 + 예외메시지 출력

   2. getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메세지 확인

   3. finally

2. 예외 발생시키기 (throw)
3. 예외 던지기

#### 예외 처리하기

- 정의 : 프로그램 실행시 발생할 수 있는 예외를 대비한 코드를 작성
- 목적 : 프로그램의 비정상 종료를 막고, 정상적인 실행상태 유지
- try catch문 이용
  - try블럭
    - 예외 발생 x : try 블럭 안에있는 실행문 실행 후 try-catch문을 빠져나가 나머지 수행
    - 예외 발생 o : try 블럭 실행문 실행 예외발생시 catch문으로 이동
      - 발생한 예외와 일치한 catch 블럭으로 이동 및 실행
      - 발생한 예외와 일치하는 catch 블럭이 없을 경우 -> 예외처리 불가

##### 예시

- 코드

        package cp8.ex8_4;

        public class Ex8_4 {

            public static void main(String[] args) {
                int i = 3;
                System.out.println(1);
                System.out.println(2);
                System.out.println(i);

                System.out.println("");

                try {
                    System.out.println("try블럭 : " + 4);
                    System.out.println("try블럭 : " + i/0);
                }
                catch(ArithmeticException ae){
                    if(ae instanceof ArithmeticException)
                        System.out.println("catch,ArithmeticException블럭 : 0으로 나누는 에러발생");

                    ae.printStackTrace();
                    System.out.println("예외 메시지 : " + ae.getMessage());
                }
                catch(Exception e){
                    System.out.println("catch,Exception : 상단 catch 블럭 외 모든 에러 ");

                }

                System.out.println("");

                System.out.println("try-catch 문 종료");
            }

        }

- 결과

        1
        2
        3

        try블럭 : 4
        catch,ArithmeticException블럭 : 0으로 나누는 에러발생
        java.lang.ArithmeticException: / by zero
            at cp8.ex8_4.Ex8_4.main(Ex8_4.java:15)
        예외 메시지 : / by zero

        try-catch 문 종료

#### finally블럭

- 예외 발생여부 상관없이 실행되어야하는 코드

- 예시

  - 프로그램 다운 받는다 가정
  - 조건 : 에러발생해도, 에러발생하지 않아도 프로그램 설치에 사용된 파일은 삭제 되어야한다.

          try{
              startInstall();
              copyFiles();
          }
          catch(Exception e){
              e.printStackTrace();
          }
          finally{
              deleteTempFiles();
          }
